spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    defer-datasource-initialization: false
  datasource:
    url: jdbc:h2:file:./src/main/resources/testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.naver.com
    port: 465
    username: b_h_woo
    password: KG5DSJ5ZPDD4
    smtp:
      auth: true
      starttls:
        enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB